version: '3'

services:
  reverse-proxy:
    image: traefik:v2.2
    command:
      - "--providers.docker"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
# Global redirection: https (www.) to https
      traefik.http.routers.wwwsecure-catchall.rule: HostRegexp(`{host:(www\.).+}`)
      traefik.http.routers.wwwsecure-catchall.entrypoints: websecure
      traefik.http.routers.wwwsecure-catchall.tls: "true"
      traefik.http.routers.wwwsecure-catchall.middlewares: wwwtohttps
# middleware: http(s)://(www.) to  https://
      traefik.http.middlewares.wwwtohttps.redirectregex.regex: ^https?://(?:www\.)?(.+)
      traefik.http.middlewares.wwwtohttps.redirectregex.replacement: https://$${1}
      traefik.http.middlewares.wwwtohttps.redirectregex.permanent: "false"

  whoami:
    image: containous/whoami
    labels:
      traefik.http.routers.whoami.entrypoints: websecure 
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.tls: "true"
      traefik.http.routers.whoami.tls.certresolver: default
      traefik.http.routers.whoami.tls.domains[0].main: whoami.localhost
      traefik.http.routers.whoami.tls.domains[0].sans: www.whoami.localhost
