version: '3'

services:
  traefik:
    image: traefik:v2.2
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.redirect-router.entrypoints=web"
      - "traefik.http.routers.redirect-router.rule=Host(`blog.localhost`)"
      - "traefik.http.routers.redirect-router.middlewares=redirect-regex"
      - "traefik.http.middlewares.redirect-regex.redirectregex.regex=^https?://blog.localhost/(.*)"
      - "traefik.http.middlewares.redirect-regex.redirectregex.replacement=http://localhost/blog/$${1}"
      - "traefik.http.middlewares.redirect-regex.redirectregex.permanent=false"

  website:
    image: nginx:latest
    volumes:
      - ./website:/usr/share/nginx/html
    labels:
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.routers.website.rule=Host(`localhost`)"

